package com.learn.api.modal;

import lombok.Data;

/**
 * @Author: luxq
 * @Description:
 * @Date: Created in 2018/5/27 0027 22:32
 */
@Data
public class SecurityScheme {

    private String type; //  	string 	Any 	REQUIRED. The type of the security scheme. Valid values are "apiKey", "http", "oauth2", "openIdConnect".
    private String description; //  	string 	Any 	A short description for security scheme. CommonMark syntax MAY be used for rich text representation.
    private String name; //  	string 	apiKey 	REQUIRED. The name of the header, query or cookie parameter to be used.
    private String in; //  	string 	apiKey 	REQUIRED. The location of the API key. Valid values are "query", "header" or "cookie".
    private String scheme; //  	string 	http 	REQUIRED. The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235.
    private String bearerFormat; //  	string 	http ("bearer") 	A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes.
    private String flows; //  	OAuth Flows Object 	oauth2 	REQUIRED. An object containing configuration information for the flow types supported.
    private String openIdConnectUrl; //  	string 	openIdConnect 	REQUIRED. OpenId Connect URL to discover OAuth2 configuration values. This MUST be in the form of a URL.

}
