// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simpleservice.proto

package com.learn.service.proto.generate.simple;

public final class SimpleServiceProtos {
  private SimpleServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_testing_SimpleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_testing_SimpleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_testing_SimpleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_testing_SimpleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023simpleservice.proto\022\014grpc.testing\"\'\n\rS" +
      "impleRequest\022\026\n\016requestMessage\030\001 \001(\t\")\n\016" +
      "SimpleResponse\022\027\n\017responseMessage\030\001 \001(\t2" +
      "\327\002\n\rSimpleService\022G\n\010UnaryRpc\022\033.grpc.tes" +
      "ting.SimpleRequest\032\034.grpc.testing.Simple" +
      "Response\"\000\022S\n\022ClientStreamingRpc\022\033.grpc." +
      "testing.SimpleRequest\032\034.grpc.testing.Sim" +
      "pleResponse\"\000(\001\022S\n\022ServerStreamingRpc\022\033." +
      "grpc.testing.SimpleRequest\032\034.grpc.testin" +
      "g.SimpleResponse\"\0000\001\022S\n\020BidiStreamingRpc" +
      "\022\033.grpc.testing.SimpleRequest\032\034.grpc.tes" +
      "ting.SimpleResponse\"\000(\0010\001BC\n\'com.learn.s" +
      "ervice.proto.generate.simpleB\023SimpleServ" +
      "iceProtosP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_testing_SimpleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_testing_SimpleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_testing_SimpleRequest_descriptor,
        new java.lang.String[] { "RequestMessage", });
    internal_static_grpc_testing_SimpleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_testing_SimpleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_testing_SimpleResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
