// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simpleservice.proto

package com.learn.service.proto.generate.simple;

/**
 * <pre>
 * A simple service for test.
 * </pre>
 *
 * Protobuf service {@code grpc.testing.SimpleService}
 */
public  abstract class SimpleService
    implements com.google.protobuf.Service {
  protected SimpleService() {}

  public interface Interface {
    /**
     * <pre>
     * Simple unary RPC.
     * </pre>
     *
     * <code>rpc UnaryRpc(.grpc.testing.SimpleRequest) returns (.grpc.testing.SimpleResponse);</code>
     */
    public abstract void unaryRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request,
        com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done);

    /**
     * <pre>
     * Simple client-to-server streaming RPC.
     * </pre>
     *
     * <code>rpc ClientStreamingRpc(stream .grpc.testing.SimpleRequest) returns (.grpc.testing.SimpleResponse);</code>
     */
    public abstract void clientStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request,
        com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done);

    /**
     * <pre>
     * Simple server-to-client streaming RPC.
     * </pre>
     *
     * <code>rpc ServerStreamingRpc(.grpc.testing.SimpleRequest) returns (stream .grpc.testing.SimpleResponse);</code>
     */
    public abstract void serverStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request,
        com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done);

    /**
     * <pre>
     * Simple bidirectional streaming RPC.
     * </pre>
     *
     * <code>rpc BidiStreamingRpc(stream .grpc.testing.SimpleRequest) returns (stream .grpc.testing.SimpleResponse);</code>
     */
    public abstract void bidiStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request,
        com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new SimpleService() {
      @java.lang.Override
      public  void unaryRpc(
          com.google.protobuf.RpcController controller,
          com.learn.service.proto.generate.simple.SimpleRequest request,
          com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done) {
        impl.unaryRpc(controller, request, done);
      }

      @java.lang.Override
      public  void clientStreamingRpc(
          com.google.protobuf.RpcController controller,
          com.learn.service.proto.generate.simple.SimpleRequest request,
          com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done) {
        impl.clientStreamingRpc(controller, request, done);
      }

      @java.lang.Override
      public  void serverStreamingRpc(
          com.google.protobuf.RpcController controller,
          com.learn.service.proto.generate.simple.SimpleRequest request,
          com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done) {
        impl.serverStreamingRpc(controller, request, done);
      }

      @java.lang.Override
      public  void bidiStreamingRpc(
          com.google.protobuf.RpcController controller,
          com.learn.service.proto.generate.simple.SimpleRequest request,
          com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done) {
        impl.bidiStreamingRpc(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.unaryRpc(controller, (com.learn.service.proto.generate.simple.SimpleRequest)request);
          case 1:
            return impl.clientStreamingRpc(controller, (com.learn.service.proto.generate.simple.SimpleRequest)request);
          case 2:
            return impl.serverStreamingRpc(controller, (com.learn.service.proto.generate.simple.SimpleRequest)request);
          case 3:
            return impl.bidiStreamingRpc(controller, (com.learn.service.proto.generate.simple.SimpleRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.learn.service.proto.generate.simple.SimpleRequest.getDefaultInstance();
          case 1:
            return com.learn.service.proto.generate.simple.SimpleRequest.getDefaultInstance();
          case 2:
            return com.learn.service.proto.generate.simple.SimpleRequest.getDefaultInstance();
          case 3:
            return com.learn.service.proto.generate.simple.SimpleRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance();
          case 1:
            return com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance();
          case 2:
            return com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance();
          case 3:
            return com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   * Simple unary RPC.
   * </pre>
   *
   * <code>rpc UnaryRpc(.grpc.testing.SimpleRequest) returns (.grpc.testing.SimpleResponse);</code>
   */
  public abstract void unaryRpc(
      com.google.protobuf.RpcController controller,
      com.learn.service.proto.generate.simple.SimpleRequest request,
      com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done);

  /**
   * <pre>
   * Simple client-to-server streaming RPC.
   * </pre>
   *
   * <code>rpc ClientStreamingRpc(stream .grpc.testing.SimpleRequest) returns (.grpc.testing.SimpleResponse);</code>
   */
  public abstract void clientStreamingRpc(
      com.google.protobuf.RpcController controller,
      com.learn.service.proto.generate.simple.SimpleRequest request,
      com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done);

  /**
   * <pre>
   * Simple server-to-client streaming RPC.
   * </pre>
   *
   * <code>rpc ServerStreamingRpc(.grpc.testing.SimpleRequest) returns (stream .grpc.testing.SimpleResponse);</code>
   */
  public abstract void serverStreamingRpc(
      com.google.protobuf.RpcController controller,
      com.learn.service.proto.generate.simple.SimpleRequest request,
      com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done);

  /**
   * <pre>
   * Simple bidirectional streaming RPC.
   * </pre>
   *
   * <code>rpc BidiStreamingRpc(stream .grpc.testing.SimpleRequest) returns (stream .grpc.testing.SimpleResponse);</code>
   */
  public abstract void bidiStreamingRpc(
      com.google.protobuf.RpcController controller,
      com.learn.service.proto.generate.simple.SimpleRequest request,
      com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.learn.service.proto.generate.simple.SimpleServiceProtos.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.unaryRpc(controller, (com.learn.service.proto.generate.simple.SimpleRequest)request,
          com.google.protobuf.RpcUtil.<com.learn.service.proto.generate.simple.SimpleResponse>specializeCallback(
            done));
        return;
      case 1:
        this.clientStreamingRpc(controller, (com.learn.service.proto.generate.simple.SimpleRequest)request,
          com.google.protobuf.RpcUtil.<com.learn.service.proto.generate.simple.SimpleResponse>specializeCallback(
            done));
        return;
      case 2:
        this.serverStreamingRpc(controller, (com.learn.service.proto.generate.simple.SimpleRequest)request,
          com.google.protobuf.RpcUtil.<com.learn.service.proto.generate.simple.SimpleResponse>specializeCallback(
            done));
        return;
      case 3:
        this.bidiStreamingRpc(controller, (com.learn.service.proto.generate.simple.SimpleRequest)request,
          com.google.protobuf.RpcUtil.<com.learn.service.proto.generate.simple.SimpleResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.learn.service.proto.generate.simple.SimpleRequest.getDefaultInstance();
      case 1:
        return com.learn.service.proto.generate.simple.SimpleRequest.getDefaultInstance();
      case 2:
        return com.learn.service.proto.generate.simple.SimpleRequest.getDefaultInstance();
      case 3:
        return com.learn.service.proto.generate.simple.SimpleRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance();
      case 1:
        return com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance();
      case 2:
        return com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance();
      case 3:
        return com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.learn.service.proto.generate.simple.SimpleService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void unaryRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request,
        com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.learn.service.proto.generate.simple.SimpleResponse.class,
          com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance()));
    }

    public  void clientStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request,
        com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.learn.service.proto.generate.simple.SimpleResponse.class,
          com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance()));
    }

    public  void serverStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request,
        com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.learn.service.proto.generate.simple.SimpleResponse.class,
          com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance()));
    }

    public  void bidiStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request,
        com.google.protobuf.RpcCallback<com.learn.service.proto.generate.simple.SimpleResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.learn.service.proto.generate.simple.SimpleResponse.class,
          com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.learn.service.proto.generate.simple.SimpleResponse unaryRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request)
        throws com.google.protobuf.ServiceException;

    public com.learn.service.proto.generate.simple.SimpleResponse clientStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request)
        throws com.google.protobuf.ServiceException;

    public com.learn.service.proto.generate.simple.SimpleResponse serverStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request)
        throws com.google.protobuf.ServiceException;

    public com.learn.service.proto.generate.simple.SimpleResponse bidiStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.learn.service.proto.generate.simple.SimpleResponse unaryRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.learn.service.proto.generate.simple.SimpleResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance());
    }


    public com.learn.service.proto.generate.simple.SimpleResponse clientStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.learn.service.proto.generate.simple.SimpleResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance());
    }


    public com.learn.service.proto.generate.simple.SimpleResponse serverStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.learn.service.proto.generate.simple.SimpleResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance());
    }


    public com.learn.service.proto.generate.simple.SimpleResponse bidiStreamingRpc(
        com.google.protobuf.RpcController controller,
        com.learn.service.proto.generate.simple.SimpleRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.learn.service.proto.generate.simple.SimpleResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.learn.service.proto.generate.simple.SimpleResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:grpc.testing.SimpleService)
}

