// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simpleservice.proto

package com.learn.service.proto.generate.simple;

public interface SimpleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.testing.SimpleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An optional string message for test.
   * </pre>
   *
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <pre>
   * An optional string message for test.
   * </pre>
   *
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
