/* ============================================================== CDM ============================================================== */

insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '黄昏，又名日夕、日暮、日晚等：此时太阳已经落山，天将黑未黑。天地昏黄，万物朦胧，故称黄昏。狗开始守门口。', '19:00-20:59', '戌时', '狗', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '平旦，又称黎明、早晨、日旦等：时是夜与日的交替之际。老虎在此时最猛。', '03:00-04:59', '寅时', '虎', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '日昳，又名日跌、日央等。太阳偏西为日跌。羊在这段时间吃草。', '13:00-14:59', '未时', '羊', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '日中，又名日正、中午等。这时候太阳最猛烈，阳气达到极限，阴气将会产生，而马是阴类动物。', '11:00-12:59', '午时', '马', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '人定，又名定昏等定，又名定昏等。此时夜色已深，人们也已经停止活动，安歇睡眠了。夜深时分猪正在熟睡。', '21:00-22:59', '亥时', '猪', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '哺时，又名日铺、夕食等。猴子喜欢在这时候啼叫。', '15:00-16:59', '申时', '猴', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '夜半，又名子夜、中夜，鼠在这时间最活跃。', '23:00-00:59', '子时', '鼠', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '隅中，又名日禺等：临近中午的时候称为隅中。蛇在这时候隐蔽在草丛中。', '09:00-10:59', '巳时', '蛇', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '日入，又名日落、日沉、傍晚。意为太阳落山的时候。鸡於傍晚开始归巢。', '17:00-18:59', '酉时', '鸡', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '日出，又名日始、破晓、旭日等。指太阳刚刚露脸，冉冉初升的那段时间。', '05:00-06:59', '卯时', '兔', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '鸡鸣，又名荒鸡，牛在这时候咀嚼白天没消化的食物。', '01:00-02:59', '丑时', '牛', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `cdm_time_segment` (id, description, segment, hour, zodiac, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), '食时，又名早食等：古人“朝食”之时也就是吃早饭时间。月亮又称玉兔，在这段时间还在天上。相传这是“群龙行雨”的时候。', '07:00-08:59', '辰时', '龙', '', 'luxq', now(), 'luxq', now(), 0, 0);

/* ============================================================== TEM ============================================================== */

/* ============================================================== UAA ============================================================== */

/* ============================================================== ZYJ ============================================================== */

insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 1, 1, '乾', 1, '乾', '乾为天', '自强不息', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 2, 8, '坤', 8, '坤', '坤为地', '厚德载物', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 3, 6, '水', 4, '雷', '水雷屯', '起始维艰', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 4, 7, '山', 6, '水', '山水蒙', '启蒙奋发', 'gua_note', '中下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 5, 6, '水', 1, '天', '水天需', '守正待机', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 6, 1, '天', 6, '水', '天水讼', '慎争戒讼', 'gua_note', '中下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 7, 8, '地', 6, '水', '地水师', '行险而顺', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 8, 6, '水', 8, '地', '水地比', '诚信团结', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 9, 5, '风', 1, '天', '风天小畜', '蓄养待进', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 10, 1, '天', 2, '泽', '天泽履', '脚踏实地', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 11, 8, '地', 1, '天', '地天泰', '应时而变', 'gua_note', '中中卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 12, 1, '天', 8, '地', '天地否', '不交不通', 'gua_note', '中中卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 13, 1, '天', 3, '火', '天火同人', '上下和同', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 14, 3, '火', 1, '天', '火天大有', '顺天依时', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 15, 8, '地', 7, '山', '地山谦', '内高外低', 'gua_note', '中中卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 16, 4, '雷', 8, '地', '雷地豫', '顺时依势', 'gua_note', '中中卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 17, 2, '泽', 4, '雷', '泽雷随', '随时变通', 'gua_note', '中中卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 18, 7, '山', 5, '风', '山风蛊', '振疲起衰', 'gua_note', '中中卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 19, 8, '地', 2, '泽', '地泽临', '教民保民', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 20, 5, '风', 8, '地', '风地观', '观下瞻上', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 21, 3, '火', 4, '雷', '火雷噬嗑', '刚柔相济', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 22, 7, '山', 3, '火', '山火贲', '饰外扬质', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 23, 7, '山', 8, '地', '山地剥', '顺势而止', 'gua_note', '中下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 24, 8, '地', 4, '雷', '地雷复', '寓动于顺', 'gua_note', '中中卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 25, 1, '天', 4, '雷', '天雷无妄', '无妄而得', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 26, 7, '山', 1, '天', '山天大畜', '止而不止', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 27, 7, '山', 4, '雷', '山雷颐', '纯正以养', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 28, 2, '泽', 5, '风', '泽风大过', '非常行动', 'gua_note', '中下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 29, 6, '坎', 6, '为', '坎为水', '行险用险', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 30, 3, '离', 3, '为', '离为火', '附和依托', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 31, 2, '泽', 7, '山', '泽山咸', '相互感应', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 32, 4, '雷', 5, '风', '雷风恒', '恒心有成', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 33, 1, '天', 7, '山', '天山遁', '遁世救世', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 34, 4, '雷', 1, '天', '雷天大壮', '壮勿妄动', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 35, 3, '火', 8, '地', '火地晋', '求进发展', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 36, 8, '地', 3, '火', '地火明夷', '晦而转明', 'gua_note', '中下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 37, 5, '风', 3, '火', '风火家人', '诚威治业', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 38, 3, '火', 2, '泽', '火泽睽', '异中求同', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 39, 6, '水', 7, '山', '水山蹇', '险阻在前', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 40, 4, '雷', 6, '水', '雷水解', '柔道致治', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 41, 7, '山', 2, '泽', '山泽损', '损益制衡', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 42, 5, '风', 4, '雷', '风雷益', '损上益下', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 43, 2, '泽', 1, '天', '泽天夬 ', '决而能和', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 44, 1, '天', 5, '风', '天风姤', '天下有风', 'gua_note', '上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 45, 2, '泽', 8, '地', '泽地萃', '荟萃聚集', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 46, 8, '地', 5, '风', '地风升', '柔顺谦虚', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 47, 2, '泽', 6, '水', '泽水困', '困境求通', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 48, 6, '水', 5, '风', '水风井', '求贤若渴', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 49, 2, '泽', 3, '火', '泽火革', '顺天应人', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 50, 3, '火', 5, '风', '火风鼎', '稳重图变', 'gua_note', '中下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 51, 4, '震', 4, '为', '震为雷', '临危不乱', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 52, 7, '艮', 7, '为', '艮为山', '动静适时', 'gua_note', '中下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 53, 5, '风', 7, '山', '风山渐', '渐进蓄德', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 54, 4, '雷', 2, '泽', '雷泽归妹', '立家兴业', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 55, 4, '雷', 3, '火', '雷火丰', '日中则斜', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 56, 3, '火', 7, '山', '火山旅', '依义顺时', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 57, 5, '巽', 5, '为', '巽为风', '谦逊受益', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 58, 2, '兑', 2, '为', '兑为泽', '刚内柔外', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 59, 5, '风', 6, '水', '风水涣', '拯救涣散', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 60, 6, '水', 2, '泽', '水泽节', '万物有节', 'gua_note', '上上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 61, 5, '风', 2, '泽', '风泽中孚', '诚信立身', 'gua_note', '下下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 62, 4, '雷', 7, '山', '雷山小过', '行动有度', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 63, 6, '水', 3, '火', '水火既济', '盛极将衰', 'gua_note', '中上卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
insert into `zyj_sixty_four_gua` (id, seq, up_seq, up_name, down_seq, down_name, gua_name, gua_yi, gua_note, gua_qian, gua_chi, gua_chi_note, xiang_yue, xiang_yue_note, tuan_yue, tuan_yue_note, qi_shi, office_code, create_by, create_date, update_by, update_date, is_deleted, version) values (REPLACE(uuid(),'-',''), 64, 3, '火', 6, '水', '火水未济', '事业未竟', 'gua_note', '中下卦', 'gua_chi', 'gua_chi_note', 'xiang_yue', 'xiang_yue_note', 'tuan_yue', 'tuan_yue_note', 'qi_shi', '', 'luxq', now(), 'luxq', now(), 0, 0);
