spring:
  profiles:
    active: dev
  application:
    name: learn-service
  flyway:
    locations: 'classpath:db/migration'
    table: learn_schema_history
  messages:
    basename: messages,i18n
  datasource:
    url: jdbc:p6spy:mysql://192.168.159.140:3306/learn?verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
      #max-evictable-idle-time-millis: 100000
      filters: stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
        session-stat-enable: true
        session-stat-max-count: 1000
        principal-session-name:
        principal-cookie-name:
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid
        #allow: '*'
        deny:
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          db-type: mysql
          config.delete-allow: false
          config.drop-table-allow: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 192.168.159.140
#    password: learn-r
    port: 16379
